### ISSUE TITLE
mac上cpu跑你的shufflenet v2检测要3.7s，好慢

### ISSUE THREAD

**Issue by zheng-yuwei** [SURFZJY/Real-time-Text-Detection#6]
在MacBook Pro，系统版本macOS 10.15.4，2.4GHz 四核 Intel Core i5，内存16G上，cpu推理，跑predict.py需要3.7s，这么慢的么，不能算real time了吧？

**Comment by Akshay-Ijantkar** [comment]
@zheng-yuwei  It takes on around 0.8 secs on my i7 CPU system

**Comment by GraceKafuu** [comment]
> @zheng-yuwei It takes on around 0.8 secs on my i7 CPU system

还是太慢了，做不到实时啊，有没有办法再快一些

**Comment by SURFZJY** [comment]
> 

这个开源项目很早的了。。我也不再维护了。或许可以看看[PaddleOCR](https://github.com/PaddlePaddle/PaddleOCR)的方案？
